export interface Person {
  name: string;
  birthYear: number;
  deathYear: number;
  category: string;
}

export const people: Person[] = [
  {
    name: "Leonardo da Vinci",
    birthYear: 1452,
    deathYear: 1519,
    category: "Art",
  },
  {
    name: "Christopher Columbus",
    birthYear: 1451,
    deathYear: 1506,
    category: "Exploration",
  },
  {
    name: "Nicolaus Copernicus",
    birthYear: 1473,
    deathYear: 1543,
    category: "Science",
  },
  { name: "Michelangelo", birthYear: 1475, deathYear: 1564, category: "Art" },
  {
    name: "Martin Luther",
    birthYear: 1483,
    deathYear: 1546,
    category: "Religion",
  },
  {
    name: "Suleiman the Magnificent",
    birthYear: 1494,
    deathYear: 1566,
    category: "Politics",
  },
  {
    name: "William Shakespeare",
    birthYear: 1564,
    deathYear: 1616,
    category: "Literature",
  },
  {
    name: "Galileo Galilei",
    birthYear: 1564,
    deathYear: 1642,
    category: "Science",
  },
  {
    name: "Johannes Kepler",
    birthYear: 1571,
    deathYear: 1630,
    category: "Science",
  },
  { name: "Rembrandt", birthYear: 1606, deathYear: 1669, category: "Art" },
  {
    name: "Isaac Newton",
    birthYear: 1643,
    deathYear: 1727,
    category: "Science",
  },
  {
    name: "John Locke",
    birthYear: 1632,
    deathYear: 1704,
    category: "Philosophy",
  },
  {
    name: "Peter the Great",
    birthYear: 1672,
    deathYear: 1725,
    category: "Politics",
  },
  {
    name: "Johann Sebastian Bach",
    birthYear: 1685,
    deathYear: 1750,
    category: "Music",
  },
  {
    name: "Voltaire",
    birthYear: 1694,
    deathYear: 1778,
    category: "Philosophy",
  },
  {
    name: "Benjamin Franklin",
    birthYear: 1706,
    deathYear: 1790,
    category: "Politics",
  },
  {
    name: "Wolfgang Amadeus Mozart",
    birthYear: 1756,
    deathYear: 1791,
    category: "Music",
  },
  {
    name: "George Washington",
    birthYear: 1732,
    deathYear: 1799,
    category: "Politics",
  },
  { name: "James Watt", birthYear: 1736, deathYear: 1819, category: "Science" },
  {
    name: "Ludwig van Beethoven",
    birthYear: 1770,
    deathYear: 1827,
    category: "Music",
  },
  {
    name: "Napoleon Bonaparte",
    birthYear: 1769,
    deathYear: 1821,
    category: "Politics",
  },
  {
    name: "Jane Austen",
    birthYear: 1775,
    deathYear: 1817,
    category: "Literature",
  },
  {
    name: "Mary Shelley",
    birthYear: 1797,
    deathYear: 1851,
    category: "Literature",
  },
  {
    name: "Charles Darwin",
    birthYear: 1809,
    deathYear: 1882,
    category: "Science",
  },
  {
    name: "Abraham Lincoln",
    birthYear: 1809,
    deathYear: 1865,
    category: "Politics",
  },
  {
    name: "Victor Hugo",
    birthYear: 1802,
    deathYear: 1885,
    category: "Literature",
  },
  {
    name: "Florence Nightingale",
    birthYear: 1820,
    deathYear: 1910,
    category: "Science",
  },
  { name: "Claude Monet", birthYear: 1840, deathYear: 1926, category: "Art" },
  {
    name: "Karl Marx",
    birthYear: 1818,
    deathYear: 1883,
    category: "Philosophy",
  },
  {
    name: "Thomas Edison",
    birthYear: 1847,
    deathYear: 1931,
    category: "Science",
  },
  {
    name: "Vincent van Gogh",
    birthYear: 1853,
    deathYear: 1890,
    category: "Art",
  },
  {
    name: "Nikola Tesla",
    birthYear: 1856,
    deathYear: 1943,
    category: "Science",
  },
  {
    name: "Sigmund Freud",
    birthYear: 1856,
    deathYear: 1939,
    category: "Philosophy",
  },
  {
    name: "Marie Curie",
    birthYear: 1867,
    deathYear: 1934,
    category: "Science",
  },
  { name: "Pablo Picasso", birthYear: 1881, deathYear: 1973, category: "Art" },
  {
    name: "Albert Einstein",
    birthYear: 1879,
    deathYear: 1955,
    category: "Science",
  },
  {
    name: "Virginia Woolf",
    birthYear: 1882,
    deathYear: 1941,
    category: "Literature",
  },
  {
    name: "Mahatma Gandhi",
    birthYear: 1869,
    deathYear: 1948,
    category: "Politics",
  },
  {
    name: "Winston Churchill",
    birthYear: 1874,
    deathYear: 1965,
    category: "Politics",
  },
  { name: "Frida Kahlo", birthYear: 1907, deathYear: 1954, category: "Art" },
  {
    name: "Martin Luther King Jr.",
    birthYear: 1929,
    deathYear: 1968,
    category: "Politics",
  },
  {
    name: "Rosa Parks",
    birthYear: 1913,
    deathYear: 2005,
    category: "Politics",
  },
  {
    name: "John F. Kennedy",
    birthYear: 1917,
    deathYear: 1963,
    category: "Politics",
  },
  {
    name: "Stephen Hawking",
    birthYear: 1942,
    deathYear: 2018,
    category: "Science",
  },
  { name: "Steve Jobs", birthYear: 1955, deathYear: 2011, category: "Science" },
];
