export interface Person {
  name: string;
  birthYear: number;
  deathYear: number;
  category: string;
}

export const people: Person[] = [
  // ART
  {
    name: "Leonardo da Vinci",
    birthYear: 1452,
    deathYear: 1519,
    category: "Art",
  },
  {
    name: "Michelangelo",
    birthYear: 1475,
    deathYear: 1564,
    category: "Art",
  },
  {
    name: "Vincent van Gogh",
    birthYear: 1853,
    deathYear: 1890,
    category: "Art",
  },
  {
    name: "Pablo Picasso",
    birthYear: 1881,
    deathYear: 1973,
    category: "Art",
  },
  {
    name: "Rembrandt",
    birthYear: 1606,
    deathYear: 1669,
    category: "Art",
  },
  {
    name: "Claude Monet",
    birthYear: 1840,
    deathYear: 1926,
    category: "Art",
  },
  {
    name: "Salvador Dalí",
    birthYear: 1904,
    deathYear: 1989,
    category: "Art",
  },
  {
    name: "Edvard Munch",
    birthYear: 1863,
    deathYear: 1944,
    category: "Art",
  },
  {
    name: "Frida Kahlo",
    birthYear: 1907,
    deathYear: 1954,
    category: "Art",
  },
  {
    name: "Johannes Vermeer",
    birthYear: 1632,
    deathYear: 1675,
    category: "Art",
  },
  {
    name: "Georgia O'Keeffe",
    birthYear: 1887,
    deathYear: 1986,
    category: "Art",
  },
  {
    name: "Andy Warhol",
    birthYear: 1928,
    deathYear: 1987,
    category: "Art",
  },
  {
    name: "Jackson Pollock",
    birthYear: 1912,
    deathYear: 1956,
    category: "Art",
  },
  {
    name: "Diego Rivera",
    birthYear: 1886,
    deathYear: 1957,
    category: "Art",
  },
  {
    name: "Caravaggio",
    birthYear: 1571,
    deathYear: 1610,
    category: "Art",
  },

  // ENTERTAINMENT
  {
    name: "Walt Disney",
    birthYear: 1901,
    deathYear: 1966,
    category: "Entertainment",
  },
  {
    name: "Charlie Chaplin",
    birthYear: 1889,
    deathYear: 1977,
    category: "Entertainment",
  },
  {
    name: "Marilyn Monroe",
    birthYear: 1926,
    deathYear: 1962,
    category: "Entertainment",
  },
  {
    name: "James Dean",
    birthYear: 1931,
    deathYear: 1955,
    category: "Entertainment",
  },
  {
    name: "Audrey Hepburn",
    birthYear: 1929,
    deathYear: 1993,
    category: "Entertainment",
  },
  {
    name: "Marlon Brando",
    birthYear: 1924,
    deathYear: 2004,
    category: "Entertainment",
  },
  {
    name: "Humphrey Bogart",
    birthYear: 1899,
    deathYear: 1957,
    category: "Entertainment",
  },
  {
    name: "Elizabeth Taylor",
    birthYear: 1932,
    deathYear: 2011,
    category: "Entertainment",
  },
  {
    name: "Paul Newman",
    birthYear: 1925,
    deathYear: 2008,
    category: "Entertainment",
  },
  {
    name: "Katharine Hepburn",
    birthYear: 1907,
    deathYear: 2003,
    category: "Entertainment",
  },
  {
    name: "Robert De Niro",
    birthYear: 1943,
    deathYear: new Date().getFullYear(),
    category: "Entertainment",
  },
  {
    name: "Al Pacino",
    birthYear: 1940,
    deathYear: new Date().getFullYear(),
    category: "Entertainment",
  },
  {
    name: "Jack Nicholson",
    birthYear: 1937,
    deathYear: new Date().getFullYear(),
    category: "Entertainment",
  },
  {
    name: "Leonardo DiCaprio",
    birthYear: 1974,
    deathYear: new Date().getFullYear(),
    category: "Entertainment",
  },
  {
    name: "Johnny Depp",
    birthYear: 1963,
    deathYear: new Date().getFullYear(),
    category: "Entertainment",
  },

  // EXPLORATION
  {
    name: "Christopher Columbus",
    birthYear: 1451,
    deathYear: 1506,
    category: "Exploration",
  },
  {
    name: "Marco Polo",
    birthYear: 1254,
    deathYear: 1324,
    category: "Exploration",
  },
  {
    name: "Ferdinand Magellan",
    birthYear: 1480,
    deathYear: 1521,
    category: "Exploration",
  },
  {
    name: "Vasco da Gama",
    birthYear: 1460,
    deathYear: 1524,
    category: "Exploration",
  },
  {
    name: "James Cook",
    birthYear: 1728,
    deathYear: 1779,
    category: "Exploration",
  },
  {
    name: "Hernán Cortés",
    birthYear: 1485,
    deathYear: 1547,
    category: "Exploration",
  },
  {
    name: "Francisco Pizarro",
    birthYear: 1478,
    deathYear: 1541,
    category: "Exploration",
  },
  {
    name: "Lewis and Clark",
    birthYear: 1774,
    deathYear: 1838,
    category: "Exploration",
  },
  {
    name: "Roald Amundsen",
    birthYear: 1872,
    deathYear: 1928,
    category: "Exploration",
  },
  {
    name: "Ernest Shackleton",
    birthYear: 1874,
    deathYear: 1922,
    category: "Exploration",
  },
  {
    name: "David Livingstone",
    birthYear: 1813,
    deathYear: 1873,
    category: "Exploration",
  },
  {
    name: "Henry Hudson",
    birthYear: 1565,
    deathYear: 1611,
    category: "Exploration",
  },
  {
    name: "Robert Peary",
    birthYear: 1856,
    deathYear: 1920,
    category: "Exploration",
  },
  {
    name: "Jacques Cousteau",
    birthYear: 1910,
    deathYear: 1997,
    category: "Exploration",
  },

  // LITERATURE
  {
    name: "William Shakespeare",
    birthYear: 1564,
    deathYear: 1616,
    category: "Literature",
  },
  {
    name: "Homer",
    birthYear: -800,
    deathYear: -701,
    category: "Literature",
  },
  {
    name: "Jane Austen",
    birthYear: 1775,
    deathYear: 1817,
    category: "Literature",
  },
  {
    name: "Charles Dickens",
    birthYear: 1812,
    deathYear: 1870,
    category: "Literature",
  },
  {
    name: "Leo Tolstoy",
    birthYear: 1828,
    deathYear: 1910,
    category: "Literature",
  },
  {
    name: "Fyodor Dostoevsky",
    birthYear: 1821,
    deathYear: 1881,
    category: "Literature",
  },
  {
    name: "Mark Twain",
    birthYear: 1835,
    deathYear: 1910,
    category: "Literature",
  },
  {
    name: "Emily Dickinson",
    birthYear: 1830,
    deathYear: 1886,
    category: "Literature",
  },
  {
    name: "Edgar Allan Poe",
    birthYear: 1809,
    deathYear: 1849,
    category: "Literature",
  },
  {
    name: "George Orwell",
    birthYear: 1903,
    deathYear: 1950,
    category: "Literature",
  },
  {
    name: "J.R.R. Tolkien",
    birthYear: 1892,
    deathYear: 1973,
    category: "Literature",
  },
  {
    name: "Virginia Woolf",
    birthYear: 1882,
    deathYear: 1941,
    category: "Literature",
  },
  {
    name: "Franz Kafka",
    birthYear: 1883,
    deathYear: 1924,
    category: "Literature",
  },
  {
    name: "Herman Melville",
    birthYear: 1819,
    deathYear: 1891,
    category: "Literature",
  },
  {
    name: "Gabriel García Márquez",
    birthYear: 1927,
    deathYear: 2014,
    category: "Literature",
  },

  // MUSIC
  {
    name: "Ludwig van Beethoven",
    birthYear: 1770,
    deathYear: 1827,
    category: "Music",
  },
  {
    name: "Wolfgang Amadeus Mozart",
    birthYear: 1756,
    deathYear: 1791,
    category: "Music",
  },
  {
    name: "Johann Sebastian Bach",
    birthYear: 1685,
    deathYear: 1750,
    category: "Music",
  },
  {
    name: "Freddie Mercury",
    birthYear: 1946,
    deathYear: 1991,
    category: "Music",
  },
  {
    name: "Elvis Presley",
    birthYear: 1935,
    deathYear: 1977,
    category: "Music",
  },
  {
    name: "Bob Dylan",
    birthYear: 1941,
    deathYear: new Date().getFullYear(),
    category: "Music",
  },
  {
    name: "Aretha Franklin",
    birthYear: 1942,
    deathYear: 2018,
    category: "Music",
  },
  {
    name: "Michael Jackson",
    birthYear: 1958,
    deathYear: 2009,
    category: "Music",
  },
  {
    name: "Madonna",
    birthYear: 1958,
    deathYear: new Date().getFullYear(),
    category: "Music",
  },
  {
    name: "Prince",
    birthYear: 1958,
    deathYear: 2016,
    category: "Music",
  },
  {
    name: "The Notorious B.I.G.",
    birthYear: 1972,
    deathYear: 1997,
    category: "Music",
  },
  {
    name: "Jimi Hendrix",
    birthYear: 1942,
    deathYear: 1970,
    category: "Music",
  },
  {
    name: "Stevie Wonder",
    birthYear: 1950,
    deathYear: new Date().getFullYear(),
    category: "Music",
  },
  {
    name: "Billie Holiday",
    birthYear: 1915,
    deathYear: 1959,
    category: "Music",
  },
  {
    name: "Elton John",
    birthYear: 1947,
    deathYear: new Date().getFullYear(),
    category: "Music",
  },

  // PHILOSOPHY
  {
    name: "Immanuel Kant",
    birthYear: 1724,
    deathYear: 1804,
    category: "Philosophy",
  },
  {
    name: "Friedrich Nietzsche",
    birthYear: 1844,
    deathYear: 1900,
    category: "Philosophy",
  },
  {
    name: "René Descartes",
    birthYear: 1596,
    deathYear: 1650,
    category: "Philosophy",
  },
  {
    name: "John Locke",
    birthYear: 1632,
    deathYear: 1704,
    category: "Philosophy",
  },
  {
    name: "Jean-Jacques Rousseau",
    birthYear: 1712,
    deathYear: 1778,
    category: "Philosophy",
  },
  {
    name: "Thomas Hobbes",
    birthYear: 1588,
    deathYear: 1679,
    category: "Philosophy",
  },
  {
    name: "Karl Marx",
    birthYear: 1818,
    deathYear: 1883,
    category: "Philosophy",
  },
  {
    name: "David Hume",
    birthYear: 1711,
    deathYear: 1776,
    category: "Philosophy",
  },
  {
    name: "Jean-Paul Sartre",
    birthYear: 1905,
    deathYear: 1980,
    category: "Philosophy",
  },
  {
    name: "Michel Foucault",
    birthYear: 1926,
    deathYear: 1984,
    category: "Philosophy",
  },
  {
    name: "Baruch Spinoza",
    birthYear: 1632,
    deathYear: 1677,
    category: "Philosophy",
  },
  {
    name: "Hannah Arendt",
    birthYear: 1906,
    deathYear: 1975,
    category: "Philosophy",
  },

  // POLITICS
  {
    name: "Julius Caesar",
    birthYear: -100,
    deathYear: -44,
    category: "Politics",
  },
  {
    name: "Augustus Caesar",
    birthYear: -63,
    deathYear: 14,
    category: "Politics",
  },
  {
    name: "Charlemagne",
    birthYear: 747,
    deathYear: 814,
    category: "Politics",
  },
  {
    name: "Genghis Khan",
    birthYear: 1162,
    deathYear: 1227,
    category: "Politics",
  },
  {
    name: "Elizabeth I",
    birthYear: 1533,
    deathYear: 1603,
    category: "Politics",
  },
  {
    name: "Louis XIV",
    birthYear: 1638,
    deathYear: 1715,
    category: "Politics",
  },
  {
    name: "Napoleon Bonaparte",
    birthYear: 1769,
    deathYear: 1821,
    category: "Politics",
  },
  {
    name: "George Washington",
    birthYear: 1732,
    deathYear: 1799,
    category: "Politics",
  },
  {
    name: "Abraham Lincoln",
    birthYear: 1809,
    deathYear: 1865,
    category: "Politics",
  },
  {
    name: "Winston Churchill",
    birthYear: 1874,
    deathYear: 1965,
    category: "Politics",
  },
  {
    name: "Mahatma Gandhi",
    birthYear: 1869,
    deathYear: 1948,
    category: "Politics",
  },
  {
    name: "Nelson Mandela",
    birthYear: 1918,
    deathYear: 2013,
    category: "Politics",
  },
  {
    name: "Theodore Roosevelt",
    birthYear: 1858,
    deathYear: 1919,
    category: "Politics",
  },
  {
    name: "Barack Obama",
    birthYear: 1961,
    deathYear: new Date().getFullYear(),
    category: "Politics",
  },
  {
    name: "Vladimir Putin",
    birthYear: 1952,
    deathYear: new Date().getFullYear(),
    category: "Politics",
  },

  // SCIENCE
  {
    name: "Isaac Newton",
    birthYear: 1643,
    deathYear: 1727,
    category: "Science",
  },
  {
    name: "Albert Einstein",
    birthYear: 1879,
    deathYear: 1955,
    category: "Science",
  },
  {
    name: "Galileo Galilei",
    birthYear: 1564,
    deathYear: 1642,
    category: "Science",
  },
  {
    name: "Charles Darwin",
    birthYear: 1809,
    deathYear: 1882,
    category: "Science",
  },
  {
    name: "Nikola Tesla",
    birthYear: 1856,
    deathYear: 1943,
    category: "Science",
  },
  {
    name: "Marie Curie",
    birthYear: 1867,
    deathYear: 1934,
    category: "Science",
  },
  {
    name: "Louis Pasteur",
    birthYear: 1822,
    deathYear: 1895,
    category: "Science",
  },
  {
    name: "Stephen Hawking",
    birthYear: 1942,
    deathYear: 2018,
    category: "Science",
  },
  {
    name: "Johannes Kepler",
    birthYear: 1571,
    deathYear: 1630,
    category: "Science",
  },
  {
    name: "Michael Faraday",
    birthYear: 1791,
    deathYear: 1867,
    category: "Science",
  },
  {
    name: "Dmitri Mendeleev",
    birthYear: 1834,
    deathYear: 1907,
    category: "Science",
  },
  {
    name: "Richard Feynman",
    birthYear: 1918,
    deathYear: 1988,
    category: "Science",
  },
  {
    name: "Gregor Mendel",
    birthYear: 1822,
    deathYear: 1884,
    category: "Science",
  },
  {
    name: "Alan Turing",
    birthYear: 1912,
    deathYear: 1954,
    category: "Science",
  },
  {
    name: "Steve Jobs",
    birthYear: 1955,
    deathYear: 2011,
    category: "Science",
  },
  {
    name: "Bill Gates",
    birthYear: 1955,
    deathYear: new Date().getFullYear(),
    category: "Science",
  },
  {
    name: "Elon Musk",
    birthYear: 1971,
    deathYear: new Date().getFullYear(),
    category: "Science",
  },
  {
    name: "Tim Berners-Lee",
    birthYear: 1955,
    deathYear: new Date().getFullYear(),
    category: "Science",
  },
];
